app:
  name: w3itch-backend
  port: 3002
  bodyParser:
    limit: 50mb
  swagger:
    enable: true
  logger:
    loki:
      enable: true
      url: 'http://127.0.0.1:3100'

db:
  host:
  port:
  username:
  password:
  database:
  charset: utf8mb4_general_ci
  timezone: 'Z' # UTC

auth:
  jwt:
    accessTokenName: 'w3itch_access_token'
    refreshTokenName: 'w3itch_refresh_token'
    accessTokenExpires: '20m'
    refreshTokenExpires: '30d'
    issuer:
    algorithm: 'RS512'
    audience: []

  cookies:
    accessTokenPath: '/'
    refreshTokenPath: '/accounts/tokens'

  cors:
    origins:
      - '*'

cache:
  redis:
    host: '127.0.0.1'
    port: 6379
    pass:
  vcode:
    ttl: 3000 # seconds

storage:
  ipfs:
    fleek:
      apiKey:
      apiSecret:
      folder: w3itch-test/attachment
    gateways:
      - https://ipfs.fleek.cob
  aws:
    accessKeyId:
    secretAccessKey:
    bucket:
    folder: w3itch-test/attachment

blockchain:
  infura:
    apiToken:
  supportedChainIds:
    test: [1, 3, 4, 5, 42]
    prod: [1, 10, 56, 137, 42161]

account:
  github:
    clientId:
    clientSecret:

user:
  username:
    reservedList:
      - blog
      - api
    # - etc.
